import '../models/exercise.dart';

class PresetExercises {
  static List<Exercise> get all => [
        Exercise(name: '杠铃深蹲', muscleGroup: '腿', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 20, maxWeight: 100, description: '核心收紧，膝盖与脚尖方向一致。', isPreset: true),
        Exercise(name: '相扑深蹲', muscleGroup: '腿', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 10, minWeight: 10, maxWeight: 60, description: '更友好的下肢变式，适合膝部不适时降强度。', isPreset: true),
        Exercise(name: '前蹲', muscleGroup: '腿', type: '复合', difficulty: '高级', defaultSets: 4, defaultReps: 6, minWeight: 20, maxWeight: 80, description: '保持躯干直立，肘部抬高。', isPreset: true),
        Exercise(name: '保加利亚分腿蹲', muscleGroup: '腿', type: '复合', difficulty: '中级', defaultSets: 3, defaultReps: 10, minWeight: 0, maxWeight: 30, description: '单腿稳定控制，重心居中。', isPreset: true),
        Exercise(name: '腿举', muscleGroup: '腿', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 12, minWeight: 40, maxWeight: 180, description: '注意膝盖轨迹，避免锁死。', isPreset: true),
        Exercise(name: '罗马尼亚硬拉', muscleGroup: '腿', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 20, maxWeight: 100, description: '髋主导发力，感受腘绳肌拉伸。', isPreset: true),
        Exercise(name: '臀桥', muscleGroup: '腿', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 12, minWeight: 0, maxWeight: 80, description: '顶部夹臀，避免腰部代偿。', isPreset: true),
        Exercise(name: '腿弯举', muscleGroup: '腿', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 10, maxWeight: 45, description: '控制离心，避免借力。', isPreset: true),
        Exercise(name: '提踵', muscleGroup: '腿', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 15, minWeight: 0, maxWeight: 60, description: '顶峰停顿 1 秒。', isPreset: true),
        Exercise(name: '硬拉', muscleGroup: '背', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 5, minWeight: 40, maxWeight: 160, description: '背部中立，杠铃贴腿。', isPreset: true),
        Exercise(name: '杠铃划船', muscleGroup: '背', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 20, maxWeight: 80, description: '肘向后拉，避免耸肩。', isPreset: true),
        Exercise(name: '引体向上', muscleGroup: '背', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 6, minWeight: 0, maxWeight: 20, description: '胸部主动找杠，控制下放。', isPreset: true),
        Exercise(name: '高位下拉', muscleGroup: '背', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 10, minWeight: 20, maxWeight: 70, description: '肩胛下沉发力。', isPreset: true),
        Exercise(name: '坐姿划船', muscleGroup: '背', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 12, minWeight: 15, maxWeight: 60, description: '保持胸椎延展。', isPreset: true),
        Exercise(name: '单臂哑铃划船', muscleGroup: '背', type: '复合', difficulty: '新手', defaultSets: 3, defaultReps: 10, minWeight: 8, maxWeight: 35, description: '减少身体旋转。', isPreset: true),
        Exercise(name: '面拉', muscleGroup: '背', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 15, minWeight: 5, maxWeight: 25, description: '强化后束与肩袖。', isPreset: true),
        Exercise(name: '直臂下压', muscleGroup: '背', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 10, maxWeight: 35, description: '保持肘微屈。', isPreset: true),
        Exercise(name: '卧推', muscleGroup: '胸', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 20, maxWeight: 100, description: '肩胛后缩下沉，稳定发力。', isPreset: true),
        Exercise(name: '上斜卧推', muscleGroup: '胸', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 15, maxWeight: 80, description: '重点刺激上胸。', isPreset: true),
        Exercise(name: '哑铃卧推', muscleGroup: '胸', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 10, minWeight: 8, maxWeight: 40, description: '轨迹自然，双侧均衡。', isPreset: true),
        Exercise(name: '双杠臂屈伸', muscleGroup: '胸', type: '复合', difficulty: '高级', defaultSets: 4, defaultReps: 8, minWeight: 0, maxWeight: 20, description: '身体略前倾，刺激胸下沿。', isPreset: true),
        Exercise(name: '俯卧撑', muscleGroup: '胸', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 15, minWeight: 0, maxWeight: 0, description: '全身一条线。', isPreset: true),
        Exercise(name: '夹胸', muscleGroup: '胸', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 5, maxWeight: 30, description: '顶峰收缩 1 秒。', isPreset: true),
        Exercise(name: '绳索飞鸟', muscleGroup: '胸', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 5, maxWeight: 25, description: '保持胸部发力，不借肩。', isPreset: true),
        Exercise(name: '肩推', muscleGroup: '肩', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 10, maxWeight: 60, description: '核心稳定，避免过度后仰。', isPreset: true),
        Exercise(name: '阿诺德推举', muscleGroup: '肩', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 10, minWeight: 6, maxWeight: 25, description: '控制旋转轨迹。', isPreset: true),
        Exercise(name: '侧平举', muscleGroup: '肩', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 12, minWeight: 3, maxWeight: 15, description: '肘带动，略高于手腕。', isPreset: true),
        Exercise(name: '前平举', muscleGroup: '肩', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 3, maxWeight: 15, description: '控制摆动。', isPreset: true),
        Exercise(name: '反向飞鸟', muscleGroup: '肩', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 15, minWeight: 3, maxWeight: 12, description: '后束主导。', isPreset: true),
        Exercise(name: '耸肩', muscleGroup: '肩', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 12, minWeight: 10, maxWeight: 40, description: '斜方肌上束刺激。', isPreset: true),
        Exercise(name: '窄握卧推', muscleGroup: '手臂', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 20, maxWeight: 80, description: '三头发力为主。', isPreset: true),
        Exercise(name: '杠铃弯举', muscleGroup: '手臂', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 10, minWeight: 10, maxWeight: 40, description: '上臂固定。', isPreset: true),
        Exercise(name: '哑铃弯举', muscleGroup: '手臂', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 5, maxWeight: 20, description: '可单侧矫正不平衡。', isPreset: true),
        Exercise(name: '锤式弯举', muscleGroup: '手臂', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 5, maxWeight: 20, description: '刺激肱肌与肱桡肌。', isPreset: true),
        Exercise(name: '绳索下压', muscleGroup: '手臂', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 12, minWeight: 10, maxWeight: 35, description: '肘部夹紧身体。', isPreset: true),
        Exercise(name: '仰卧臂屈伸', muscleGroup: '手臂', type: '孤立', difficulty: '中级', defaultSets: 3, defaultReps: 10, minWeight: 8, maxWeight: 30, description: '离心控制。', isPreset: true),
        Exercise(name: '集中弯举', muscleGroup: '手臂', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 4, maxWeight: 15, description: '顶峰停顿。', isPreset: true),
        Exercise(name: '仰卧卷腹', muscleGroup: '核心', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 15, minWeight: 0, maxWeight: 15, description: '感受腹部卷曲。', isPreset: true),
        Exercise(name: '平板支撑', muscleGroup: '核心', type: '孤立', difficulty: '新手', defaultSets: 4, defaultReps: 45, minWeight: 0, maxWeight: 0, description: '以秒为单位记录。', isPreset: true),
        Exercise(name: '悬垂举腿', muscleGroup: '核心', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 12, minWeight: 0, maxWeight: 0, description: '避免身体摆动。', isPreset: true),
        Exercise(name: '俄罗斯转体', muscleGroup: '核心', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 20, minWeight: 0, maxWeight: 15, description: '旋转来自躯干。', isPreset: true),
        Exercise(name: '死虫', muscleGroup: '核心', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 0, maxWeight: 0, description: '强化核心稳定。', isPreset: true),
        Exercise(name: '农夫行走', muscleGroup: '核心', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 30, minWeight: 10, maxWeight: 40, description: '以米或秒计时。', isPreset: true),
        Exercise(name: '推雪橇', muscleGroup: '腿', type: '复合', difficulty: '高级', defaultSets: 6, defaultReps: 20, minWeight: 40, maxWeight: 120, description: '强化爆发与下肢耐力。', isPreset: true),
        Exercise(name: '哈克深蹲', muscleGroup: '腿', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 10, minWeight: 20, maxWeight: 120, description: '稳定轨迹，关注股四头。', isPreset: true),
        Exercise(name: 'T 杠划船', muscleGroup: '背', type: '复合', difficulty: '中级', defaultSets: 4, defaultReps: 8, minWeight: 20, maxWeight: 80, description: '减少下背代偿。', isPreset: true),
        Exercise(name: '胸托划船', muscleGroup: '背', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 10, minWeight: 10, maxWeight: 50, description: '支撑充分，更适合新手。', isPreset: true),
        Exercise(name: '上斜哑铃飞鸟', muscleGroup: '胸', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 4, maxWeight: 15, description: '控制底部拉伸。', isPreset: true),
        Exercise(name: '地雷杆推举', muscleGroup: '肩', type: '复合', difficulty: '新手', defaultSets: 4, defaultReps: 10, minWeight: 10, maxWeight: 35, description: '肩友好型推举。', isPreset: true),
        Exercise(name: '臂屈伸机', muscleGroup: '手臂', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 12, minWeight: 10, maxWeight: 40, description: '重点刺激三头。', isPreset: true),
        Exercise(name: '卷腹机', muscleGroup: '核心', type: '孤立', difficulty: '新手', defaultSets: 3, defaultReps: 15, minWeight: 10, maxWeight: 35, description: '收缩时呼气。', isPreset: true),
      ];
}
